POST {{apiUrl}}/route/1/review
Authorization: {{ authorizationToken }}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="enjoy.png"

< ./../../main/resources/mock/images/enjoy.png

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="enjoy2.png"

< ./../../main/resources/mock/images/enjoy2.png

--WebAppBoundary
Content-Disposition: form-data; name="content"

Create Review!
--WebAppBoundary
Content-Disposition: form-data; name="score"

5.0
--WebAppBoundary--

###
POST {{apiUrl}}/route/1/review
Authorization: {{ authorizationToken }}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content"

Create Review Without File!
--WebAppBoundary
Content-Disposition: form-data; name="score"

3.6
--WebAppBoundary--

###
GET {{apiUrl}}/route/1/reviews?size=10&page=1&sortType=best
Authorization: {{ authorizationToken }}

###
POST {{apiUrl}}/route/review/16
Authorization: {{ authorizationToken }}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="fileChange"

false

--WebAppBoundary
Content-Disposition: form-data; name="content"

Update Review!zzz
--WebAppBoundary
Content-Disposition: form-data; name="score"

3.5

###
POST {{apiUrl}}/route/review/8
Authorization: {{ authorizationToken }}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content"

Update Review!
--WebAppBoundary
Content-Disposition: form-data; name="score"

3.5
--WebAppBoundary--

###
POST {{apiUrl}}/route/review/7/like
Authorization: {{ authorizationToken }}

###
DELETE {{apiUrl}}/route/review/9
Authorization: {{ authorizationToken }}

