POST {{apiUrl}}/auth/register
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="email";

{{TEST_USER_EMAIL}}
--boundary
Content-Disposition: form-data; name="password";

{{TEST_USER_PASSWORD}}
--boundary
Content-Disposition: form-data; name="name";

testname
--boundary
Content-Disposition: form-data; name="avatar"; filename="enjoy.png"

< ./../main/resources/mock/images/enjoy.png
--boundary

###
POST {{apiUrl}}/auth/login
Content-Type: application/json

{"email": "{{TEST_USER_EMAIL}}", "password": "{{TEST_USER_PASSWORD}}"}

> {%
client.global.set("authorizationToken", "Bearer " + response.body.accessToken);
client.global.set("refreshToken", "Bearer " + response.body.refreshToken);
client.log("Auth Token : " + client.global.get("authorizationToken"));
client.log("RefreshToken : " + client.global.get("refreshToken"));
%}

###
GET {{apiUrl}}/auth/me
Content-Type: application/json
Authorization: {{authorizationToken}}