POST {{apiUrl}}/cart/place
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "id": 1797997961,
  "name": "옥동식 서교점",
  "url": "https://place.map.kakao.com/1797997961",
  "x": 37.554619995803215,
  "y": 126.91083170563417,
  "address": "서울 마포구 양화로7길 44-10 (우)04035",
  "categoryId": "CE7",
  "categoryName": "카페"
}

###

POST {{apiUrl}}/cart/place
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "id": 1440347564,
  "name": "커피 한약방",
  "url": "https://place.map.kakao.com/1440347564",
  "x": 37.554619995803215,
  "y": 126.91083170563417,
  "address": "서울 중구 삼일대로12길 16-6 (우)04542",
  "categoryId": "CE7",
  "categoryName": "카페"
}

###

GET {{apiUrl}}/cart/my
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

###

PUT {{apiUrl}}/cart/place/1797997961/memo
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "memo": "아메리카노"
}

###

DELETE {{apiUrl}}/cart/place/1797997961
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

###

DELETE {{apiUrl}}/cart/place
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}


