GET {{apiUrl}}/place/1440347564?id=1440347564&name=커피 한약방&address=서울 중구 삼일대로12길 16-6 (우)04542&url=https://place.map.kakao.com/1440347564&x=37.554619995803215&y=126.91083170563417&categoryId=CE7
Content-Type: application/json
Authorization: {{ authorizationToken }}

###

GET {{apiUrl}}/place/1440347564
Content-Type: application/json
Authorization: {{ authorizationToken }}

###

GET {{apiUrl}}/place/1797997961/review?size=5&page=1&sortType=best
Content-Type: application/json
Authorization: {{ authorizationToken }}

###

POST {{apiUrl}}/place/1797997961/review
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{ authorizationToken }}

--boundary
Content-Disposition: form-data; name="content";

Hello Content
--boundary
Content-Disposition: form-data; name="score";

4.5
--boundary
Content-Disposition: form-data; name="images"; filename="enjoy.png"

< ./../main/resources/mock/images/enjoy.png


###

POST {{apiUrl}}/place/1440347564/review/9
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{ authorizationToken }}

--boundary
Content-Disposition: form-data; name="content";

Updated Content
--boundary
Content-Disposition: form-data; name="score";

3.5


###

DELETE {{apiUrl}}/place/123/review/2
Content-Type: application/json
Authorization: {{ authorizationToken }}

###

POST {{apiUrl}}/place/1440347564/like
Content-Type: application/json
Authorization: {{ authorizationToken }}

###

POST {{apiUrl}}/place/1440347564/review/8/like
Content-Type: application/json
Authorization: {{ authorizationToken }}
