###

POST {{apiUrl}}/route
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "name": "나의 테스트 경로",
  "places": [
    {
      "id" : 1797997961,
      "order" : 1
    },
    {
      "id" : 1440347564,
      "order" : 2
    }
  ]
}

###

PUT {{apiUrl}}/route/3
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "firstPlaceId": 1797997961,
  "secondPlaceId": 1440347564
}

###

PUT {{apiUrl}}/route/1/place
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "place": {
    "id" : 123,
    "image" : "https://www.gn.go.kr/tour/images/tour/main_new/mvisual_img07.jpg",
    "name" : "강남",
    "url" : "https://www.gn.go.kr/tour/index.do",
    "x" : 37.748125,
    "y" : 128.878996,
    "category" : "CE7",
    "order" : 1
    }
}

###

GET {{apiUrl}}/route/3
Authorization: {{ authorizationToken }}

###

GET {{apiUrl}}/routes/my
Authorization: {{ authorizationToken }}

###

POST {{apiUrl}}/route/1/like
Content-Type: application/json
Authorization: {{ authorizationToken }}

###

POST {{apiUrl}}/route/1/review
Authorization: {{ authorizationToken }}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="enjoy.png"

< C:\Users\Administrator\Desktop\baruntravel\baruntravel\backend\api\src\main\resources\mock\images\enjoy.png

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="enjoy2.png"

< C:\Users\Administrator\Desktop\baruntravel\baruntravel\backend\api\src\main\resources\mock\images\enjoy2.png

--WebAppBoundary
Content-Disposition: form-data; name="content"

Create Review!
--WebAppBoundary
Content-Disposition: form-data; name="score"

5.0
--WebAppBoundary--

###

POST {{apiUrl}}/route/1/review
Authorization: {{ authorizationToken }}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content"

Create Review Without File!
--WebAppBoundary
Content-Disposition: form-data; name="score"

5.0
--WebAppBoundary--

###

GET {{apiUrl}}/route/1/reviews
Authorization: {{ authorizationToken }}

###

POST {{apiUrl}}/route/review/1
Authorization: {{ authorizationToken }}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="enjoy2.png"

< C:\Users\Administrator\Desktop\baruntravel\baruntravel\backend\api\src\main\resources\mock\images\enjoy2.png

--WebAppBoundary
Content-Disposition: form-data; name="content"

Update Review!
--WebAppBoundary
Content-Disposition: form-data; name="score"

3.5
--WebAppBoundary--

###

POST {{apiUrl}}/route/review/1/like
Authorization: {{ authorizationToken }}

###

DELETE {{apiUrl}}/route/review/4
Authorization: {{ authorizationToken }}


