POST {{apiUrl}}/route/empty
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "name": "Test Name Route"
}

###

POST {{apiUrl}}/route
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "name": "나의 테스트 경로",
  "places": [
    {
      "id" : 123,
      "image" : "https://www.gn.go.kr/tour/images/tour/main_new/mvisual_img07.jpg",
      "name" : "강릉바닷가",
      "url" : "https://www.gn.go.kr/tour/index.do",
      "x" : 37.748125,
      "y" : 128.878996,
      "category" : "FD6",
      "order" : 1
    },
    {
      "id" : 124,
      "image" : "https://cf.bstatic.com/xdata/images/hotel/270x200/129750773.jpg?k=d338049190ff48b19261ee5f516ee563aaeb8aeb97c4774c1e171e402cf25891&o=",
      "name" : "강릉 어린이집",
      "url" : "https://kr.hotels.com/go/south-korea/kr-best-gangneung-things-to-do",
      "x" : 37.748130,
      "y" : 128.8789333,
      "category" : "CE7",
      "order" : 2
    }
  ]
}

###

PUT {{apiUrl}}/route/1
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "name": "수정된 테스트 경로 ",
  "places": [
    {
      "id" : 123,
      "image" : "https://www.gn.go.kr/tour/images/tour/main_new/mvisual_img07.jpg",
      "name" : "강남",
      "url" : "https://www.gn.go.kr/tour/index.do",
      "x" : 37.748125,
      "y" : 128.878996,
      "category" : "FD6",
      "order" : 1
    },
    {
      "id" : 124,
      "image" : "https://cf.bstatic.com/xdata/images/hotel/270x200/129750773.jpg?k=d338049190ff48b19261ee5f516ee563aaeb8aeb97c4774c1e171e402cf25891&o=",
      "name" : "홍대",
      "url" : "https://kr.hotels.com/go/south-korea/kr-best-gangneung-things-to-do",
      "x" : 37.748130,
      "y" : 128.8789333,
      "category" : "CE7",
      "order" : 2
    }
  ]
}

###

PUT {{apiUrl}}/route/1/place
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "place": {
    "id" : 123,
    "image" : "https://www.gn.go.kr/tour/images/tour/main_new/mvisual_img07.jpg",
    "name" : "강남",
    "url" : "https://www.gn.go.kr/tour/index.do",
    "x" : 37.748125,
    "y" : 128.878996,
    "category" : "CE7",
    "order" : 1
    }
}

###

GET {{apiUrl}}/route/1
Authorization: {{ authorizationToken }}

###

GET {{apiUrl}}/routes/my
Authorization: {{ authorizationToken }}
